### ISSUE TITLE
Inconsistent attribute: Integer type with float values.

### ISSUE THREAD

**Issue by taliaga** [Fiware/showcase.IDS.ZeroDefects#3]
As requested by @jmcanterafonseca , I quickly tested this with quantumleap. I discovered an inconsistency in the script for some attributes. See below an example, declaring Integer type with float value.

`"axis_IV_load":{"type":"Integer","value":"5.2","metadata":{}},`

Using Number as type should solve the issue. Other than cases like that, the rest of the entities seem to be persisted OK.

**Comment by jmcanterafonseca** [comment]
thanks, @taliaga , please could you make a tiny PR to fix that?

**Comment by jgato** [comment]
Great This should be fixed just changing the type in the configuration
file.

**Comment by taliaga** [comment]
I'll let you guys fix this as you see better fit. Ping me if you encounter any other issues.

**Comment by jgato** [comment]
I have changed they type.
Tip: If we need to change or adapt the config.json this could be customized and used inside the container in that way:

```
```
$> docker run -e ORION_URL=ORION_HOST:ORION_PORT -v /tmp/custom_config.json:/usr/src/app/config/config.json  -it jgato/fiware-milling script.py MM_data_output/Transfer_data_MPT_18_Impeller_0002_ref_APS_ok.csv
```

```
